version: '3.4'
services:
  worker:
    build: .
    image: &img worker
    command: [celery, worker, --app=worker.app, --pool=gevent, --concurrency=20, --loglevel=INFO]
    environment: &env
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - MINIO_HOST=minio:9000
      - MINIO_ACCESS_KEY=pinacatestjob
      - MINIO_SECRET_KEY=testing1234
      - HIT_COUNT=100
      - API_URL=https://5ju149k98f.execute-api.ap-south-1.amazonaws.com/pinacatestjob_beta
      - TASK_SCHEDULE=100
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./app:/app

  worker-minio:
    build: .
    image: *img
    command: [celery, worker, --app=worker.app, --pool=gevent, --concurrency=20, --queues=minio, --loglevel=INFO]
    environment: *env
    depends_on:
      - beat
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./app:/app

  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.app, --loglevel=INFO]
    environment: *env
    depends_on: 
      - rabbitmq
    restart: 'no'
    volumes: 
      - ./app:/app

  rabbitmq:
    image: rabbitmq:3.7.8

  minio:
    image: minio/minio:RELEASE.2018-11-06T01-01-02Z
    command: server /export
    environment: *env
    ports:
      - 80:9000
    volumes:
      - minio:/data

volumes:
  minio: